site_name: My Docs
nav:
  - Introduction: "index.md"
  - Extern:
      - Api-Seite: "extern/api.md"
  - Intern:
      - Kontakt: "intern/contact.md"
      - Doku: "intern/documentation.md"
  - Feedback: "feedback.md"
theme:
  name: material
